services:
  web:
    build: "apache/"
    ports:
      - "80:80"
    networks:
      rede_test:
        aliases:
          - server1.lan
          - server2.lan
    volumes:
      - "./apache/server1.conf:/etc/apache2/sites-enabled/server1.conf"
      - "./apache/server2.conf:/etc/apache2/sites-enabled/server2.conf"
      - "./web:/web"
  cliente:
    build: "cliente/"
    networks:
      - rede_test

networks:
  rede_test:
    driver: bridge